# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestInDjango', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
