# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '\u041f\u0440\u043e\u0434\u0443\u043a\u0442', 'verbose_name_plural': '\u041f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='skidka',
            options={'verbose_name': '\u0421\u043a\u0438\u0434\u043a\u0430', 'verbose_name_plural': '\u0421\u043a\u0438\u0434\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brendProduct', to='design.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupProduct', to='design.Category'),
        ),
        migrations.AlterField(
            model_name='skidka',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brendSkidka', to='design.Category'),
        ),
        migrations.AlterField(
            model_name='skidka',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupSkidka', to='design.Category'),
        ),
        migrations.AlterField(
            model_name='skidka',
            name='unitProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.Product'),
        ),
        migrations.AlterField(
            model_name='skidka',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
